version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:
