version: '3'
services:
  app:
    build: .
    ports:
      - '9000:9000'
    environment:
      - PORT=9000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 52280930
      POSTGRES_DB: books_db
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
